---
layout: post
comments: true
tags: [diary]
---

= 2019-04-29 Daily Post

:doctype: book
:icons: font
:source-highlighter: coderay
:toc: top
:toclevels: 3
:sectlinks:
:numbered:

== Google Analytics

구글 어낼리틱스에서 유용하고 사용할만한 몇가지 기능을 알게되었다.
사용법도 조금씩 익혀가고 있다.
아직은 블로그에 달아놓기만 하고 제대로 활용하고있지 못한데 사용법을 조금씩 익히면서 유의미한 데이터를 볼 수 있는 방법을 조금씩 찾아봐야겠다.

== 현금영수증 용도변경

어제 홈택스에 용도변경신청을 했는데 오늘 답변이 왔다.
접수가 완료됐고, 변경되는데 1주일정도 걸린다고 한다.
생각보다 오래 걸리기는 하지만 되는게 어디야 기다려야지.

== Fiddler

아직 사용법이 익숙하진 않지만 fiddler를 통해 웹 요청을 확인한다.
주로 브라우저 개발자툴을 이용하기는 하지만 화면전환이 일어나는 곳에서는 피들러를 사용하고 있다.
피들러에서 프록시 설정을 하고, 모바일 기기에서 wifi 설정에서 프록시 설정을 하면 피들러를 사용하는 pc를 프록시할 수 있다.
http 뿐만 아니라 https도 약간의 설정과 신뢰과정을 거치면 요청을 중간에 가로챌 수 있다.
모바일 앱에서 요청을 보내고 그 요청을 피들러가 있는 프록시 서버에서 가로채서 요청/반환 값을 변조할 수 있다.
신뢰 과정을 거쳐야하기 때문에 해킹을 하는데 사용하기는 어렵지만 장난치기 좋을것 같다.

== Grails

망할 grails는 아무리 봐도 줏대가 없다.
프레임워크에서 사용하는 변수인데도 언제는 콜렉션 객체였다가 언제는 문자열 객체가 된다.
계층파괴는 둘째치고 이건 진짜 좀 너무하는거 아닌가?
마음에 드는건 기본 테스트 Framework로 Spock를 사용한다는거 하나뿐이다.

== etc

봄이여서 그런지 벌이 많이 나오고있다. 무섭다.
내일은 근로자의날이라 쉰다 너무 좋다 ^^

끄읕!