---
layout: post
comments: true
tags: [diary]
---

= 2019-04-29 Daily Post

:doctype: book
:icons: font
:source-highlighter: coderay
:toc: top
:toclevels: 3
:sectlinks:
:numbered:

얼마나 자주, 오래 할 지는 모르겠지만 오늘부터는 가급적 그 날 알게된 것이나 겪은 일을 블로그에 기록하려 한다.
개발과 관련된 내용일 수도 있고, 전혀 관련없는 내용일 수도 있다.
그냥 글쓰기 연습겸 일기장처럼, 낙서장처럼 끄적일 것이다.

== 현금영수증 용도변경

얼마 전 티켓팅에 성공해서 스프링캠프에 참석을 했다.
참석 이후 회사에 비용처리를 위해 현금영수증을 발급받아 정산신청을 했는데 알고보니 개인소득공제용으로 발급되어 지출증빙용으로 용도변경을 해야 했다.
회사에서 비용처리를 하는 것이니 당연했던 것인데 티켓팅을 할 당시 무조건 빠르게한다는 생각으로 현금영수증에 대한 고민은 1도 하지 않았었다.
이 때문에 소득공제용으로 발급된 현금영수증을 지출증빙용으로 용도변경을 해야 했는데, 우선 주최측에 메일로 문의를 해보았다.
주최측에 문의를 하고나서 왠지 주최측에서도 할 수 없을 것 같다는 생각을 하고 있었는데, 지인을 통해서 국세청에서 직접 용도변경을 할 수 있다는 사실을 알게되었다.(thanks for wang)
국세청에 문의해본 결과 인터넷으로 용도변경 신청시 필요한 서류는 신분증 사본(주민등록증, 운전면허증, 여권)과 건 별 내역서 혹은 현금영수증 사본(날짜, 승인번호 9자리, 금액이 모두 기재되어 있어야 함, 홈택스에서 다운 가능)이 필요하다는 답변을 받았다.
또한, 소비자 발급수단관리에 지출증빙 귀속 사업장이 입력되어있어야 한다고 한다.
그래서 필요한 서류를 준비해서 국세청에 용도변경 신청을 했다.
그 이후 저녁에 주최측으로부터 회신을 받았는데, 현금영수증과 관련된 부분은 티켓을 판매한 사이트인 네이버페이에 문의해보라는 답변을 받았다.
어차피 국세청에서 용도변경이 가능한 것 같으니 그냥 국세청 답변을 기다려야겠다.

== Browser Request Content Type

브라우저에서 웹 서버로 요청을 보내면 무조건 Request Header에 Content Type이 포함된다고 생각하고 있었다.
그런데 오늘 보니 그게 아니였다. 그냥 GET 요청이면 Request Header에 Content Type이 포함되지 않는다.
이게 특정 브라우저에서만 그런지 모든 브라우저에서 동일한 것인지 까지는 확인해보지 않았지만 처음 알게된 사실이다.

== apache poi

엑셀과 관련된 기능을 처리하기 위해 많이 사용하는 라이브러리다.
이 apache poi가 특정 버전에서 특정 버전으로(minor) 올라가면서 어떤 기능의 기본 값(default value)이 바뀐다는 것을 얼마전에 알게 되었다.
오늘 버전을 올리면서 기본 값 뿐만 아니라 이 라이브러리를 사용하여 템플릿(?)처럼 기능을 제공하는 다른 라이브러리에서도 버전호환성이 맞지 않아 문제가 발생한다는 것을 알게되었다.

== Grails Filter

Grails의 Filter에서 uri로 필터를 지정할 수 있다는 것을 알고 있었다.
uri에 \\**를 사용해서 하위 경로를 포함시켜 필터를 적요할 수 있다.
그런데 서로 다른 패턴으로 동일한 필터를 적용시킬 수 있을 줄 알았는데 적용이 안된다.
controller로 조건을 걸 때는 'example\*|sample\*' 처럼 여러 패턴을 하나의 필터에 적용할 수 있는데 uri는 안된다.
uri도 여러 패턴을 적용할 수 있게 해줬으면 좋겠다는 생각을 한다.

== asciidoc

블로그를 asciidoc을 쓰고 travisCI를 통해 빌드를 해서 githu page로 관리를 하는데,
이 글을 쓰면서 특수문자 치환방지를 위해서 역슬래시(\)를 쓰면 된다는 것을 알게됐다.
그런데 역슬래시를 쓰고싶은데 역슬래시 치환방지는 어떻게 하는거지? 그냥 쓰면 되나?
일단 그냥 써봐야지

== 업무

담당하고 있는 업무와 관련해서 이전에 어떤 일을 해달라는 요청을 받았는데, 요청받았을 당시 특정 데이터도 바꿔야 된다는 사실을 망각하고 바꾸지 않았다.
그 데이터를 바꿔달라는 요청은 아니였고 요청자체가 그 데이터와 관련이 있었던 것도 아니였지만 그 때 좀만 더 생각했으면 그 데이터를 바꿀 수 있었을텐데 아주 깨끗하게 생각하지 못했다.
그래서 그 데이터와 관련된 오류 리포팅을 받았다. 다음부터는 좀 더 꼼꼼히 살피고 잘 생각해봐야겠다.

그런데 업무하고 관련된 기록을 남겨도 되려나? 상세한 내용없이 대충 적는것이니 상관없겠지?

== etc

스프링캠프 참석 이후 자극을 받게 되었고, 이제 다시 공부를 조금씩 시작하려고 한다.
아예 안한 것은 아니지만 했다고 볼 수도 없었다.
책을 폈는데 눈에 들어오지 않는다.
오랫만에 하는거니깐 처음부터 무리하지 말아야겠다.

이 글쓰기도 정말 얼마나 오래할 지 모르겠다.
매일은 아니더라도 가끔 한번씩은 써야지 라고 생각하고 있는데 첫날부터 이런 생각을 하는 것을 보면 정말 오래 못쓰겠지 싶다.
블로그도 쓰는 김에 카테고리 정리도 조만간 해야겠다.

끄읕!