---
layout: post
comments: true
tags: [diary]
---

= 2019-05-12 Daily Post

:doctype: book
:icons: font
:source-highlighter: coderay
:toc: top
:toclevels: 3
:sectlinks:
:numbered:

== 클로저

자바스크립트의 클로저 개념을 4년만에 이해했다.
지금은 이해하고있지만 곧 다시 잊고 헷갈릴지도 모르겠다.
자바스크립트를 그냥 사용만 해보고 요즘 처음으로 공부해보고 있는데 알고있으면 도움이 많이 될 것 같다.
이것도 언젠가는 블로그에 정리해야겠다.

== Angular JS

Angular JS? Angular? 버전 올라가면서 1과 2~가 부르는 명칭이 다르다했는데 기억이 안난다.
프론트엔드에 대해서 잘 모르고 실무에서는 프레임워크를 안써봐서 프론트엔드 프레임워크에 대해서는 잘 모르는데, 최근에 조금 보니 좋은것 같다.
Angular JS는 별로 좋지않다고 들었던 것 같은데 악명(?)에 비해서는 프론트엔드 멍청이가 보기에는 꽤나 좋은 프레임워크인 것 같다.

== Google Analytics

Google Analytics는 생각보다 많은 정보를 수집해서 가지고 있다.
브라우저 정보부터 사용자 행동패턴까지 수집한 정보를 가공해서 많은 부분에 활용할 수 있도록 한다.
Google Analytics의 API에 대해서 보고 있는데, Google Analytics에서 웹 클라이언트로 제공해주는 사이트보다 훨씬 많은 것을 할 수 있는 것 같다.
필터링의 경우 사이트에서는 일부 제약이 있지만 API를 사용하면 제약이 많이 없어진다.
조회 성능때문에 제약을 걸어둔건가 싶기도 한데 좀 더 알아봐야겠다.
정리가 어느정도 되면 포스트 작성해야겠다.

== 잡담

최근들어 평일에는 어렵지만 주말에는 가급적이면 운동을 하고있다.
이제 2주째인데 주말에만 하면 살이 안빠지려나 싶다.
평일에도 할 수 있으면 해야지 싶은데 퇴근하면 만사가 귀찮으니 하려나 싶다.
그래도 술은 많이 줄였으니 조금은 가능성이 있어보인다.
정 안되면 스트레칭정도라도 하려고 노력해봐야겠다.

블로그는 1일 단위로 작성하려했는데 점점 1주일 단위가 되고있다.
1일 단위로 쓰면 내용이 별로 없기도 하고 평일에는 만사가 귀찮아서 안하게되는 것 같다.
그래도 노력이라도 해봐야겠다. 일기라도 쓸까...